import { item } from './items'

/* eslint-disable */
export const girls = {
  'Ayane': {
    name: 'Ayane',
    lovesItems: [
      { item: item('Opera Glasses') },
    ],
    likesItems: [
      { item: item('Blue RC Airplane') },
      { item: item('Crab'), degree: '*' },
      { item: item('Cream Soda'), degree: '*' },
      { item: item('Fancy Basket') },
      { item: item('Frilled Parasol') },
      { item: item('Japanese Parasol'), degree: '±' },
      { item: item('Legendary Scarab'), degree: '±' },
      { item: item('Magnifying Glass') },
      { item: item('Marrons Glaces'), degree: '*±' },
      { item: item('Music Book') },
      { item: item('Novel: Bridge To Space') },
      { item: item('Ocarina') },
      { item: item('Purple Volleyball') },
      { item: item('Purple Windmill') },
      { item: item('Rainbow Flying Disc') },
      { item: item('Succulent Grapes'), degree: '*' },
      { item: item('Sushi'), degree: '*' },
      { item: item('Tomato'), degree: '*' },
    ],
  },
  'Helena': {
    name: 'Helena',
    lovesItems: [
      { item: item('Frilled Parasol') },
    ],
    likesItems: [
      { item: item('Blancmange'), degree: '*±' },
      { item: item('Dumbbell') },
      { item: item('Hand Basket') },
      { item: item('Iced Tea'), degree: '*' },
      { item: item('Lyre') },
      { item: item('Novel: Swept From The Sea') },
      { item: item('Opera Glasses') },
      { item: item('Peacock Fan') },
      { item: item('Pocket Watch'), degree: '±' },
      { item: item('Quality Muskmelon'), degree: '*' },
      { item: item('Red Watering Can') },
      { item: item('Romance Novel') },
      { item: item('Sky Blue RC Car') },
      { item: item('Sunset Flying Disc') },
      { item: item('Tea Set'), degree: '±' },
      { item: item('Tengu Fan') },
      { item: item('White Volleyball') },
      { item: item('Yellow Wind Chime') },
    ],
  },
  'Hitomi': {
    name: 'Hitomi',
    lovesItems: [
      { item: item('Fancy Basket') },
    ],
    likesItems: [
      { item: item('Blue Volleyball') },
      { item: item('Cabbage'), degree: '*' },
      { item: item('Chocolate'), degree: '*' },
      { item: item('Cloth Bag') },
      { item: item('Lyrical Poetry Book') },
      { item: item('Magnifying Glass') },
      { item: item('Novel: Bridge To Space') },
      { item: item('Orange Juice'), degree: '*' },
      { item: item('Red Windmill'), degree: '±' },
      { item: item('Romance Novel') },
      { item: item('Sachertorte'), degree: '*±' },
      { item: item('Soft-Serve Ice Cream'), degree: '*' },
      { item: item('Succulent Tangerines'), degree: '*' },
      { item: item('Tea Set'), degree: '±' },
      { item: item('Toaster Oven'), degree: '±' },
      { item: item('Violin') },
      { item: item('White Watering Can') },
      { item: item('Yellow RC Airplane') },
    ],
  },
  'Honoka': {
    name: 'Honoka',
    lovesItems: [
      { item: item('Yellow RC Airplane') },
    ],
    likesItems: [
      { item: item('Cream Puff'), degree: '*±' },
      { item: item('Donut'), degree: '*' },
      { item: item('Electric Guitar') },
      { item: item('French Fries'), degree: '*' },
      { item: item('Fried Chicken'), degree: '*' },
      { item: item('Juicy Peach'), degree: '*' },
      { item: item('Laptop') },
      { item: item('Lemon Soda'), degree: '*' },
      { item: item('Mister Moo'), degree: '±' },
      { item: item('Pink Bag') },
      { item: item('Pink Windmill') },
      { item: item('Pizza'), degree: '*' },
      { item: item('Pocket Watch'), degree: '±' },
      { item: item('Red Wind Chime') },
      { item: item('Sky Blue RC Car') },
      { item: item('Soft-Serve Ice Cream'), degree: '*' },
      { item: item('Tomato'), degree: '*' },
    ],
  },
  'Kasumi': {
    name: 'Kasumi',
    lovesItems: [
      { item: item('Kasumi Coin') },
    ],
    likesItems: [
      { item: item('Artist Set') },
      { item: item('Blue Wind Chime') },
      { item: item('Encyclopedia') },
      { item: item('Four Leaf Clover'), degree: '*' },
      { item: item('Iced Cafe Au Lait'), degree: '*' },
      { item: item('Large Strawberry'), degree: '*' },
      { item: item('Legendary Scarab'), degree: '±' },
      { item: item('Newspaper') },
      { item: item('Novel: The Blue Bird') },
      { item: item('Recorder') },
      { item: item('Red Pinwheel'), degree: '±' },
      { item: item('Strawberry Millefeuille'), degree: '*±' },
      { item: item('Sunset Flying Disc') },
      { item: item('Sushi'), degree: '*' },
      { item: item('Telescope') },
      { item: item('White Watering Can') },
      { item: item('Windmill Dagger'), degree: '±' },
    ],
  },
  'Kokoro': {
    name: 'Kokoro',
    lovesItems: [
      { item: item('Tea Ceremony Set') },
    ],
    likesItems: [
      { item: item('Anmitsu'), degree: '*±' },
      { item: item('Coconut Juice'), degree: '*' },
      { item: item('Crystal') },
      { item: item('Dart Set') },
      { item: item('Fried Chicken'), degree: '*' },
      { item: item('Houseplant'), degree: '*' },
      { item: item('Japanese Parasol'), degree: '±' },
      { item: item('Laptop') },
      { item: item('Mister Moo') },
      { item: item('Music Book') },
      { item: item('Neon Orange Volleyball') },
      { item: item('Novel: Endless Galaxy') },
      { item: item('Pink Bag') },
      { item: item('Pink Pinwheel') },
      { item: item('Red Watering Can') },
      { item: item('Round Watermelon'), degree: '*' },
      { item: item('Taiko Drum') },
      { item: item('Tengu Mask'), degree: '±' },
      { item: item('Yellow Wind Chime') },
    ],
  },
  'Leifang': {
    name: 'Leifang',
    lovesItems: [
      { item: item('Annin Tofu'), degree: '*±' },
    ],
    likesItems: [
      { item: item('Aroma Oil') },
      { item: item('Cabbage'), degree: '*' },
      { item: item('Chinese Tea'), degree: '*' },
      { item: item('Crystal') },
      { item: item('Dumbbell') },
      { item: item('Erhu') },
      { item: item('French Fries'), degree: '*' },
      { item: item('Gold Trumpet') },
      { item: item('Juicy Peach'), degree: '*' },
      { item: item('Lantern') },
      { item: item('Novel: Endless Galaxy') },
      { item: item('Peacock Fan') },
      { item: item('Pink Bag') },
      { item: item('Rainbow Flying Disc') },
      { item: item('Recorder') },
      { item: item('Red Wind Chime') },
      { item: item('Romance Novel') },
      { item: item('Silver Trumpet') },
      { item: item('Soft-Serve Ice Cream'), degree: '*' },
    ],
  },
  'Marie Rose': {
    name: 'Marie Rose',
    lovesItems: [
      { item: item('Novel: Endless Galaxy') },
    ],
    likesItems: [
      { item: item('Artist Set') },
      { item: item('Black RC Car') },
      { item: item('Blue RC Airplane') },
      { item: item('Blue Volleyball') },
      { item: item('Blue Wind Chime') },
      { item: item('Cabbage'), degree: '*' },
      { item: item('Cheesecake'), degree: '*' },
      { item: item('Crab'), degree: '*' },
      { item: item('Fruit Punch'), degree: '*' },
      { item: item('Hand Basket') },
      { item: item('Harmonica') },
      { item: item('Lantern') },
      { item: item('Orange Watering Can') },
      { item: item('Pizza'), degree: '*' },
      { item: item('Prinsessbakelse'), degree: '*±' },
      { item: item('Sky Blue Flying Disc') },
      { item: item('Sky Blue RC Car') },
    ],
  },
  'Misaki': {
    name: 'Misaki',
    lovesItems: [
      { item: item('Mango Vanilla Crepe'), degree: '*±' },
    ],
    likesItems: [
      { item: item('Microphone') },
      { item: item('Tapioca Milk Tea'), degree: '*' },
      { item: item('Telescope') },
    ],
  },
  'Momiji': {
    name: 'Momiji',
    lovesItems: [
      { item: item('Encyclopedia') },
    ],
    likesItems: [
      { item: item('Big Pineapple'), degree: '*' },
      { item: item('Cloth Bag') },
      { item: item('Fresh Banana'), degree: '*' },
      { item: item('Houseplant'), degree: '*' },
      { item: item('Iced Cafe Au Lait'), degree: '*' },
      { item: item('Kasumi Coin') },
      { item: item('Lyrical Poetry Book') },
      { item: item('Newspaper') },
      { item: item('Novel: The Blue Bird') },
      { item: item('Orange Watering Can') },
      { item: item('Purple Windmill') },
      { item: item('Rainbow Flying Disc') },
      { item: item('Red Volleyball') },
      { item: item('Red Wind Chime') },
      { item: item('Silver Trumpet') },
      { item: item('Sushi'), degree: '*' },
      { item: item('Tea Ceremony Set') },
      { item: item('Toaster Oven'), degree: '±' },
      { item: item('Windmill Dagger'), degree: '±' },
      { item: item('Yokan Jelly'), degree: '*±' },
    ],
  },
  'Nyotengu': {
    name: 'Nyotengu',
    lovesItems: [
      { item: item('Crystal') },
    ],
    likesItems: [
      { item: item('Black RC Car') },
      { item: item('Chocolate'), degree: '*' },
      { item: item('Dart Set') },
      { item: item('French Fries'), degree: '*' },
      { item: item('Four Leaf Clover'), degree: '*' },
      { item: item('Gold Trumpet') },
      { item: item('Iced Coffee'), degree: '*' },
      { item: item('Lantern') },
      { item: item('Manju'), degree: '*±' },
      { item: item('Novel: Swept From The Sea') },
      { item: item('Peacock Fan') },
      { item: item('Red Apple'), degree: '*' },
      { item: item('Sky Blue Flying Disc') },
      { item: item('Telescope') },
      { item: item('Tengu Fan') },
      { item: item('Tengu Mask'), degree: '±' },
    ],
  },
}

Object.keys(girls).forEach(x => girls[x].id = x)

export const girlsList = Object.values(girls)
export const girl = (id) => {
  const r = girls[id]
  if (!r) throw new Error(`missing girl ${id}`)
  return r
}