/* eslint-disable */
export const items = {
  'Anmitsu': { name: 'Anmitsu' },
  'Annin Tofu': { name: 'Annin Tofu' },
  'Aroma Oil': { name: 'Aroma Oil' },
  'Artist Set': { name: 'Artist Set' },
  'Big Pineapple': { name: 'Big Pineapple' },
  'Black RC Car': { name: 'Black RC Car' },
  'Blancmange': { name: 'Blancmange' },
  'Blue RC Airplane': { name: 'Blue RC Airplane' },
  'Blue Volleyball': { name: 'Blue Volleyball' },
  'Blue Wind Chime': { name: 'Blue Wind Chime' },
  'Cabbage': { name: 'Cabbage' },
  'Cheesecake': { name: 'Cheesecake' },
  'Chinese Tea': { name: 'Chinese Tea' },
  'Chocolate': { name: 'Chocolate' },
  'Cloth Bag': { name: 'Cloth Bag' },
  'Coconut Juice': { name: 'Coconut Juice' },
  'Crab': { name: 'Crab' },
  'Cream Puff': { name: 'Cream Puff' },
  'Cream Soda': { name: 'Cream Soda' },
  'Crystal': { name: 'Crystal' },
  'Dart Set': { name: 'Dart Set' },
  'Donut': { name: 'Donut' },
  'Dumbbell': { name: 'Dumbbell' },
  'Electric Guitar': { name: 'Electric Guitar' },
  'Encyclopedia': { name: 'Encyclopedia' },
  'Erhu': { name: 'Erhu' },
  'Fancy Basket': { name: 'Fancy Basket' },
  'Four Leaf Clover': { name: 'Four Leaf Clover' },
  'French Fries': { name: 'French Fries' },
  'Fresh Banana': { name: 'Fresh Banana' },
  'Fried Chicken': { name: 'Fried Chicken' },
  'Frilled Parasol': { name: 'Frilled Parasol' },
  'Fruit Punch': { name: 'Fruit Punch' },
  'Gold Trumpet': { name: 'Gold Trumpet' },
  'Hand Basket': { name: 'Hand Basket' },
  'Harmonica': { name: 'Harmonica' },
  'Houseplant': { name: 'Houseplant' },
  'Iced Cafe Au Lait': { name: 'Iced Cafe Au Lait' },
  'Iced Coffee': { name: 'Iced Coffee' },
  'Iced Tea': { name: 'Iced Tea' },
  'Japanese Parasol': { name: 'Japanese Parasol' },
  'Juicy Peach': { name: 'Juicy Peach' },
  'Kasumi Coin': { name: 'Kasumi Coin' },
  'Lantern': { name: 'Lantern' },
  'Laptop': { name: 'Laptop' },
  'Large Strawberry': { name: 'Large Strawberry' },
  'Legendary Scarab': { name: 'Legendary Scarab' },
  'Lemon Soda': { name: 'Lemon Soda' },
  'Lyre': { name: 'Lyre' },
  'Lyrical Poetry Book': { name: 'Lyrical Poetry Book' },
  'Magnifying Glass': { name: 'Magnifying Glass' },
  'Mango Vanilla Crepe': { name: 'Mango Vanilla Crepe' },
  'Manju': { name: 'Manju' },
  'Marrons Glaces': { name: 'Marrons Glaces' },
  'Microphone': { name: 'Microphone' },
  'Mister Moo': { name: 'Mister Moo' },
  'Music Book': { name: 'Music Book' },
  'Neon Orange Volleyball': { name: 'Neon Orange Volleyball' },
  'Newspaper': { name: 'Newspaper' },
  'Novel: Bridge To Space': { name: 'Novel: Bridge To Space' },
  'Novel: Endless Galaxy': { name: 'Novel: Endless Galaxy' },
  'Novel: Swept From The Sea': { name: 'Novel: Swept From The Sea' },
  'Novel: The Blue Bird': { name: 'Novel: The Blue Bird' },
  'Ocarina': { name: 'Ocarina' },
  'Opera Glasses': { name: 'Opera Glasses' },
  'Orange Juice': { name: 'Orange Juice' },
  'Orange Watering Can': { name: 'Orange Watering Can' },
  'Peacock Fan': { name: 'Peacock Fan' },
  'Pink Bag': { name: 'Pink Bag' },
  'Pink Pinwheel': { name: 'Pink Pinwheel' },
  'Pink Windmill': { name: 'Pink Windmill' },
  'Pizza': { name: 'Pizza' },
  'Pocket Watch': { name: 'Pocket Watch' },
  'Prinsessbakelse': { name: 'Prinsessbakelse' },
  'Purple Volleyball': { name: 'Purple Volleyball' },
  'Purple Windmill': { name: 'Purple Windmill' },
  'Quality Muskmelon': { name: 'Quality Muskmelon' },
  'Rainbow Flying Disc': { name: 'Rainbow Flying Disc' },
  'Recorder': { name: 'Recorder' },
  'Red Apple': { name: 'Red Apple' },
  'Red Pinwheel': { name: 'Red Pinwheel' },
  'Red Volleyball': { name: 'Red Volleyball' },
  'Red Watering Can': { name: 'Red Watering Can' },
  'Red Wind Chime': { name: 'Red Wind Chime' },
  'Red Windmill': { name: 'Red Windmill' },
  'Romance Novel': { name: 'Romance Novel' },
  'Round Watermelon': { name: 'Round Watermelon' },
  'Sachertorte': { name: 'Sachertorte' },
  'Silver Trumpet': { name: 'Silver Trumpet' },
  'Sky Blue Flying Disc': { name: 'Sky Blue Flying Disc' },
  'Sky Blue RC Car': { name: 'Sky Blue RC Car' },
  'Soft-Serve Ice Cream': { name: 'Soft-Serve Ice Cream' },
  'Strawberry Millefeuille': { name: 'Strawberry Millefeuille' },
  'Succulent Grapes': { name: 'Succulent Grapes' },
  'Succulent Tangerines': { name: 'Succulent Tangerines' },
  'Sunset Flying Disc': { name: 'Sunset Flying Disc' },
  'Sushi': { name: 'Sushi' },
  'Taiko Drum': { name: 'Taiko Drum' },
  'Tapioca Milk Tea': { name: 'Tapioca Milk Tea' },
  'Tea Ceremony Set': { name: 'Tea Ceremony Set' },
  'Tea Set': { name: 'Tea Set' },
  'Telescope': { name: 'Telescope' },
  'Tengu Fan': { name: 'Tengu Fan' },
  'Tengu Mask': { name: 'Tengu Mask' },
  'Toaster Oven': { name: 'Toaster Oven' },
  'Tomato': { name: 'Tomato' },
  'Violin': { name: 'Violin' },
  'White Volleyball': { name: 'White Volleyball' },
  'White Watering Can': { name: 'White Watering Can' },
  'Windmill Dagger': { name: 'Windmill Dagger' },
  'Yellow RC Airplane': { name: 'Yellow RC Airplane' },
  'Yellow Wind Chime': { name: 'Yellow Wind Chime' },
  'Yokan Jelly': { name: 'Yokan Jelly' },
}

Object.keys(items).forEach(x => items[x].id = x)

export const itemsList = Object.values(items)
export const item = (id) => {
  const r = items[id]
  if (!r) throw new Error(`missing item ${id}`)
  return r
}
